name: Python Testing and Linting workflow
run-name: Testing [${{ github.ref_name }}]
on: push

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install requirements
      run: python3 -m pip install ".[dev]" --user
    - name: Test and Lint
      run: make test-all
