name: Python Testing and Linting workflow
run-name: Testing ${{ github.ref_name }}
on: push

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: pip install .[dev]
    - name: Test and Lint
      run: make test-all
